"""unique constraint on exam_attempts exam_id student_id

Revision ID: b972846c3f36
Revises: d58062f16446
Create Date: 2026-08-08 17:14:20.860051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b972846c3f36'
down_revision: Union[str, None] = 'd58062f16446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_exam_attempts_exam_student', 'exam_attempts', ['exam_id', 'student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_exam_attempts_exam_student', 'exam_attempts', type_='unique')
    # ### end Alembic commands ###
