"""widen violations type column for copy_paste_attempt

Revision ID: dc5ddb4ad988
Revises: b972846c3f36
Create Date: 2026-08-09 12:29:54.782465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5ddb4ad988'
down_revision: Union[str, None] = 'b972846c3f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('violations', 'type',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('tab_switch', 'fullscreen_exit', 'copy_paste_attempt', 'other', name='violation_type', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('violations', 'type',
               existing_type=sa.Enum('tab_switch', 'fullscreen_exit', 'copy_paste_attempt', 'other', name='violation_type', native_enum=False),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
